spring.profiles.active: test
spring.application.name: project

---
server:
 port: 10107
spring:
 profiles: dev
 jpa:
  database-platform: org.hibernate.dialect.Oracle10gDialect
project.datasource:
 url: jdbc:oracle:thin:@localhost:1521/xe
 username: test
 password: test
 driver-class-name: oracle.jdbc.OracleDriver
---
server:
 port: 10107
spring:
 profiles: test
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
 h2:
    console:
      enabled: true
project.datasource:
 url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
 username: sa
 password: 
 driverClassName: org.h2.Driver